name: Archive
on:
  push:
  workflow_dispatch:
  schedule:
    # Update every 6 hours, at quarter past to avoid top of hour load.
    - cron: '15 4,10,16,22 * * *'

jobs:
  build:
    permissions:
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      - run: make -j index.html

      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
